export const africaQuiz = [
  {
    question: "The Sahara Desert is located in which part of Africa?",
    options: ["North", "South", "East", "West"],
    correct_answer: "North",
    difficulty: "easy",
  },
  {
    question: "Which is the largest country in Africa by area?",
    options: ["Nigeria", "South Africa", "Sudan", "Algeria"],
    correct_answer: "Algeria",
    difficulty: "medium",
  },
  {
    question:
      "True or False: Africa is the second largest continent by land area.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "medium",
  },
  {
    question: "Which river is the longest in Africa?",
    options: ["Nile", "Congo", "Niger", "Zambezi"],
    correct_answer: "Nile",
    difficulty: "easy",
  },
  {
    question: "What is the capital city of Kenya?",
    options: ["Nairobi", "Lagos", "Addis Ababa", "Cairo"],
    correct_answer: "Nairobi",
    difficulty: "easy",
  },
  {
    question: "True or False: The official language of Angola is Portuguese.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "medium",
  },
  {
    question: "Which African country is known as the 'Rainbow Nation'?",
    options: ["Nigeria", "Kenya", "South Africa", "Ghana"],
    correct_answer: "South Africa",
    difficulty: "medium",
  },
  {
    question: "Which is the highest mountain in Africa?",
    options: ["Mount Kenya", "Mount Kilimanjaro", "Mount Elgon", "Drakensberg"],
    correct_answer: "Mount Kilimanjaro",
    difficulty: "hard",
  },
  {
    question: "What is the primary currency used in South Africa?",
    options: ["Rand", "Naira", "Pound", "Dollar"],
    correct_answer: "Rand",
    difficulty: "medium",
  },
  {
    question:
      "True or False: The African Union (AU) is headquartered in Addis Ababa, Ethiopia.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "hard",
  },
  {
    question: "Which country is known as the 'Land of a Thousand Hills'?",
    options: ["Rwanda", "Uganda", "Kenya", "Tanzania"],
    correct_answer: "Rwanda",
    difficulty: "hard",
  },
  {
    question: "True or False: Africa has the world's largest rainforest.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "hard",
  },
  {
    question: "Which African country has the largest population?",
    options: ["Egypt", "Ethiopia", "Nigeria", "South Africa"],
    correct_answer: "Nigeria",
    difficulty: "medium",
  },
  {
    question: "True or False: Lake Victoria is the largest lake in Africa.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "easy",
  },
  {
    question: "Which country is known for its ancient pyramids?",
    options: ["Egypt", "Sudan", "Morocco", "Ethiopia"],
    correct_answer: "Egypt",
    difficulty: "easy",
  },
  {
    question: "What is the official language of Senegal?",
    options: ["English", "French", "Portuguese", "Spanish"],
    correct_answer: "French",
    difficulty: "medium",
  },
  {
    question: "Which African country was never colonized?",
    options: ["Liberia", "Ethiopia", "Ghana", "Tanzania"],
    correct_answer: "Ethiopia",
    difficulty: "medium",
  },
  {
    question: "True or False: Africa is the birthplace of humanity.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "medium",
  },
  {
    question: "Which ocean borders Africa to the east?",
    options: [
      "Atlantic Ocean",
      "Indian Ocean",
      "Southern Ocean",
      "Pacific Ocean",
    ],
    correct_answer: "Indian Ocean",
    difficulty: "easy",
  },
  {
    question: "Which African city is known as the 'Mother City'?",
    options: ["Lagos", "Cairo", "Cape Town", "Nairobi"],
    correct_answer: "Cape Town",
    difficulty: "medium",
  },
  {
    question: "What is the main religion in North Africa?",
    options: ["Christianity", "Islam", "Hinduism", "Buddhism"],
    correct_answer: "Islam",
    difficulty: "easy",
  },
  {
    question:
      "Which African country is famous for its Serengeti National Park?",
    options: ["Kenya", "Tanzania", "Uganda", "South Africa"],
    correct_answer: "Tanzania",
    difficulty: "medium",
  },
  {
    question:
      "True or False: The Horn of Africa includes Somalia and Ethiopia.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "medium",
  },
  {
    question: "What is the capital city of Ghana?",
    options: ["Accra", "Lagos", "Abuja", "Kampala"],
    correct_answer: "Accra",
    difficulty: "easy",
  },
  {
    question: "Which African river flows through the most countries?",
    options: ["Nile", "Congo", "Niger", "Zambezi"],
    correct_answer: "Nile",
    difficulty: "hard",
  },
  {
    question: "What is the largest island in Africa?",
    options: ["Madagascar", "Zanzibar", "Mauritius", "Seychelles"],
    correct_answer: "Madagascar",
    difficulty: "medium",
  },
  {
    question:
      "True or False: The Great Rift Valley runs through Eastern Africa.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "easy",
  },
  {
    question:
      "Which African country is known for its Pharaonic temples and tombs?",
    options: ["Morocco", "Nigeria", "Egypt", "South Africa"],
    correct_answer: "Egypt",
    difficulty: "medium",
  },
  {
    question: "What is the primary export of Nigeria?",
    options: ["Gold", "Diamonds", "Oil", "Cocoa"],
    correct_answer: "Oil",
    difficulty: "medium",
  },
  {
    question: "True or False: Africa has 54 recognized sovereign states.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "hard",
  },
  {
    question: "Which desert is located in Southern Africa?",
    options: ["Sahara", "Kalahari", "Gobi", "Namib"],
    correct_answer: "Kalahari",
    difficulty: "medium",
  },
  {
    question: "Which African country is famous for its wine production?",
    options: ["Morocco", "South Africa", "Algeria", "Kenya"],
    correct_answer: "South Africa",
    difficulty: "medium",
  },
  {
    question: "Which country is known as the 'Pearl of Africa'?",
    options: ["Uganda", "Kenya", "Tanzania", "Rwanda"],
    correct_answer: "Uganda",
    difficulty: "hard",
  },
  {
    question:
      "True or False: The Sahara Desert is larger than the United States.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "hard",
  },
  {
    question: "Which is the oldest independent country in Africa?",
    options: ["Ethiopia", "Liberia", "Egypt", "Morocco"],
    correct_answer: "Ethiopia",
    difficulty: "hard",
  },
  {
    question: "What is the predominant climate in Central Africa?",
    options: ["Desert", "Tropical Rainforest", "Savanna", "Mediterranean"],
    correct_answer: "Tropical Rainforest",
    difficulty: "medium",
  },
  {
    question: "Which country is Africa's largest producer of cocoa?",
    options: ["Ghana", "Ivory Coast", "Nigeria", "Cameroon"],
    correct_answer: "Ivory Coast",
    difficulty: "medium",
  },
  {
    question: "True or False: The official language of Mozambique is Spanish.",
    options: ["True", "False"],
    correct_answer: "False",
    difficulty: "easy",
  },
  {
    question:
      "Which African lake is known for its high biodiversity of cichlid fish?",
    options: ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"],
    correct_answer: "Lake Malawi",
    difficulty: "hard",
  },
  {
    question: "Which African country has the most UNESCO World Heritage Sites?",
    options: ["South Africa", "Ethiopia", "Morocco", "Egypt"],
    correct_answer: "South Africa",
    difficulty: "hard",
  },
  {
    question:
      "True or False: The Sahel is a region that separates the Sahara Desert from the Savannas.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "medium",
  },
  {
    question: "Which African country is home to the ancient city of Timbuktu?",
    options: ["Mali", "Niger", "Chad", "Sudan"],
    correct_answer: "Mali",
    difficulty: "hard",
  },
  {
    question: "What is the official language of Somalia?",
    options: ["Arabic", "Somali", "Swahili", "English"],
    correct_answer: "Somali",
    difficulty: "medium",
  },
  {
    question: "Which African country is known for its rich diamond mines?",
    options: ["Botswana", "Ghana", "South Africa", "Namibia"],
    correct_answer: "Botswana",
    difficulty: "medium",
  },
  {
    question: "True or False: Madagascar is part of the African continent.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "easy",
  },
  {
    question: "Which African country has the city of Casablanca?",
    options: ["Tunisia", "Morocco", "Algeria", "Egypt"],
    correct_answer: "Morocco",
    difficulty: "medium",
  },
  {
    question: "What is the capital city of Ethiopia?",
    options: ["Addis Ababa", "Kampala", "Nairobi", "Accra"],
    correct_answer: "Addis Ababa",
    difficulty: "medium",
  },
  {
    question: "Which African country is home to the historic region of Nubia?",
    options: ["Egypt", "Sudan", "Libya", "Ethiopia"],
    correct_answer: "Sudan",
    difficulty: "hard",
  },
  {
    question: "True or False: The Great Sphinx of Giza is located in Morocco.",
    options: ["True", "False"],
    correct_answer: "False",
    difficulty: "easy",
  },
  {
    question: "What is the capital city of Zambia?",
    options: ["Lusaka", "Harare", "Gaborone", "Windhoek"],
    correct_answer: "Lusaka",
    difficulty: "medium",
  },
  {
    question:
      "Which African country is known for the ancient rock-hewn churches of Lalibela?",
    options: ["Ethiopia", "Kenya", "Uganda", "Tanzania"],
    correct_answer: "Ethiopia",
    difficulty: "hard",
  },
  {
    question: "What is the primary language spoken in Ghana?",
    options: ["Swahili", "English", "French", "Akan"],
    correct_answer: "English",
    difficulty: "medium",
  },
  {
    question:
      "True or False: The Congo River is the deepest river in the world.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "hard",
  },
  {
    question: "Which African country has the largest number of pyramids?",
    options: ["Egypt", "Sudan", "Ethiopia", "Morocco"],
    correct_answer: "Sudan",
    difficulty: "hard",
  },
  {
    question: "What is the capital city of Senegal?",
    options: ["Dakar", "Bamako", "Ouagadougou", "Accra"],
    correct_answer: "Dakar",
    difficulty: "medium",
  },
  {
    question: "Which African country is famous for its spice island, Zanzibar?",
    options: ["Kenya", "Tanzania", "Mozambique", "Madagascar"],
    correct_answer: "Tanzania",
    difficulty: "medium",
  },
  {
    question: "True or False: The Nile River flows northward through Africa.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "easy",
  },
  {
    question: "Which African country is home to the Victoria Falls?",
    options: ["Zambia", "Zimbabwe", "Mozambique", "Botswana"],
    correct_answer: ["Zambia", "Zimbabwe"],
    difficulty: "medium",
  },
  {
    question: "What is the official language of Algeria?",
    options: ["Arabic", "French", "Berber", "English"],
    correct_answer: "Arabic",
    difficulty: "medium",
  },
  {
    question: "Which African country is known for its production of coffee?",
    options: ["Ethiopia", "Kenya", "Uganda", "Rwanda"],
    correct_answer: "Ethiopia",
    difficulty: "medium",
  },
  {
    question: "True or False: Africa is home to the world's largest desert.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "medium",
  },
  {
    question: "What is the capital city of Botswana?",
    options: ["Gaborone", "Windhoek", "Lusaka", "Harare"],
    correct_answer: "Gaborone",
    difficulty: "medium",
  },
  {
    question: "Which African country was formerly known as Abyssinia?",
    options: ["Ethiopia", "Eritrea", "Somalia", "Djibouti"],
    correct_answer: "Ethiopia",
    difficulty: "hard",
  },
  {
    question: "True or False: The Okavango Delta is located in Namibia.",
    options: ["True", "False"],
    correct_answer: "False",
    difficulty: "medium",
  },
  {
    question: "Which African island nation is located in the Indian Ocean?",
    options: ["Cape Verde", "Seychelles", "Mauritius", "Comoros"],
    correct_answer: "Seychelles",
    difficulty: "medium",
  },
  {
    question: "What is the currency of Kenya?",
    options: ["Shilling", "Dollar", "Rand", "Naira"],
    correct_answer: "Shilling",
    difficulty: "medium",
  },
  {
    question:
      "Which African country is known for its annual wildebeest migration?",
    options: ["South Africa", "Kenya", "Botswana", "Tanzania"],
    correct_answer: ["Kenya", "Tanzania"],
    difficulty: "medium",
  },
  {
    question: "True or False: The Serengeti National Park is located in Kenya.",
    options: ["True", "False"],
    correct_answer: "False",
    difficulty: "medium",
  },
  {
    question: "Which African country has the oldest university in the world?",
    options: ["Egypt", "Morocco", "Ethiopia", "Sudan"],
    correct_answer: "Morocco",
    difficulty: "hard",
  },
  {
    question: "What is the capital city of Namibia?",
    options: ["Windhoek", "Gaborone", "Lusaka", "Harare"],
    correct_answer: "Windhoek",
    difficulty: "medium",
  },
  {
    question:
      "Which African country is known for the ancient city of Carthage?",
    options: ["Tunisia", "Libya", "Morocco", "Egypt"],
    correct_answer: "Tunisia",
    difficulty: "hard",
  },
  {
    question: "True or False: Africa is the continent with the most countries.",
    options: ["True", "False"],
    correct_answer: "True",
    difficulty: "medium",
  },
  {
    question: "Which African lake is the world's second deepest?",
    options: ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"],
    correct_answer: "Lake Tanganyika",
    difficulty: "hard",
  },
  {
    question: "What is the official language of Rwanda?",
    options: ["English", "French", "Swahili", "Kinyarwanda"],
    correct_answer: "Kinyarwanda",
    difficulty: "medium",
  },
  {
    question: "Which African country is known for the pyramids of Meroë?",
    options: ["Egypt", "Sudan", "Libya", "Ethiopia"],
    correct_answer: "Sudan",
    difficulty: "hard",
  },
];
